###################################
# Window
####################################

[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
opacity = 0.8

####################################
# Font
####################################

[font]
size = 18.0
# normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

####################################
# Cursor
####################################

[cursor]
style = { shape = "Block", blinking = "Off" }
unfocused_hollow = true
thickness = 0.2

####################################
# Mouse
####################################

[mouse]
hide_when_typing = true

####################################
# Key bindings
####################################

[keyboard]
bindings = [
    { key = "Back", mods = "Control", chars = "\u0017" },
    { key = "Enter", mods = "Control|Shift", chars = "\u0017" },
]
